pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                withMaven( maven: 'maven-3.9.0'){
                  sh 'mvn -f java-tomcat-sample/pom.xml clean package'
                }
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Create Tomcat Docker Image'){
            steps {
                sh "pwd"
                sh "ls -a"
                sh "docker build ./java-tomcat-sample-docker -t tomcatsamplewebapp:${env.BUILD_ID}"
            }
        }

    }
}
